'use client';
import {useState,useEffect,useCallback} from 'react';
import MayhemSync from './mayhem-sync';
import {Trophy,Swords,ShieldCheck} from 'lucide-react';
import {Table} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
const date=(v:string)=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
const localNow=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const TIERS=[{name:'Recruta do Caos',min:0},{name:'Brutamontes de Bronze',min:15},{name:'Vanguarda Prateada',min:30},{name:'Carrasco Dourado',min:60},{name:'Senhor de Platina',min:100},{name:'Soberano Diamante',min:160},{name:'Lenda do Caos',min:250}];
const tierFor=(points:number)=>{let index=0;for(let i=0;i<TIERS.length;i++)if(points>=TIERS[i].min)index=i;const tier=TIERS[index],next=TIERS[index+1];return {...tier,index,next,remaining:next?next.min-points:0}};
const TierIcon=({index,name}:{index:number;name:string})=><span className="tier-icon" style={{backgroundPosition:`${index*100/6}% center`}} role="img" aria-label={name}/>;
export default function Mayhem({admin}:{admin:boolean}) {
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [open,setOpen]=useState(false),[mode,setMode]=useState('riot'),[matchId,setMatchId]=useState(''),[playedAt,setPlayedAt]=useState(localNow),[choices,setChoices]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false);
 const [voidId,setVoidId]=useState(''),[reason,setReason]=useState('');
 const reload=useCallback(async()=>{const r=await fetch('/api/mayhem',{cache:'no-store'}),b:any=await r.json();if(!r.ok)throw new Error(b.error);setData(b)},[]);
 useEffect(()=>{reload().catch(e=>setError(e.message));const timer=setInterval(()=>reload().catch(()=>{}),20000);return()=>clearInterval(timer)},[reload]);
 async function save(payload:any) {
  setBusy(true);setError('');setNotice('');
  try {const r=await fetch('/api/mayhem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),b:any=await r.json();if(!r.ok)throw new Error(b.error);await reload();setOpen(false);setVoidId('');setNotice(payload.action==='void'?'Partida anulada. Classificação Mayhem recalculada.':'Resultado salvo no ranking Mayhem.');}
  catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}
 }
 const players=data?.ranking||[],matches=data?.matches||[],results=data?.results||[],leader=players.find((p:any)=>p.games>0),activeMatches=matches.filter((m:any)=>!m.void_reason),totalWins=players.reduce((n:number,p:any)=>n+p.wins,0),activePlayers=players.filter((p:any)=>p.games>0).length;
 const leaderTier=leader?tierFor(leader.points):tierFor(0),leaderProgress=leaderTier.next?Math.max(0,Math.min(100,(leader.points-leaderTier.min)/(leaderTier.next.min-leaderTier.min)*100)):100;
 return <div className="mayhem">
  <section className="panel mayhem-hero">
   <div className="mayhem-hero-copy"><span className="mayhem-season"><Swords size={14}/> TEMPORADA DO CAOS</span><p className="eyebrow">LIGA DA COMUNIDADE · ARAM MAYHEM</p><h2>Domine o caos.<br/><em>Conquiste seu elo.</em></h2><p>Vitórias valem pontos, pontos elevam seu tier. Suba da linha de frente até se tornar uma Lenda do Caos.</p><div className="mayhem-hero-actions"><span className="badge"><ShieldCheck size={14}/> Liga independente</span><span><Swords size={15}/> Vitória +3 pontos</span></div></div>
   <div className="mayhem-leader"><div className="leader-crown"><Trophy size={18}/> LÍDER DA TEMPORADA</div>{leader?<><TierIcon index={leaderTier.index} name={leaderTier.name}/><strong>{leader.name}</strong><span className="leader-tier">{leaderTier.name}</span><div className="leader-score"><b>{leader.points}</b><small>PONTOS</small><i></i><b>{leader.wins}</b><small>VITÓRIAS</small></div>{leaderTier.next&&<div className="tier-progress"><div><span>Próximo: {leaderTier.next.name}</span><strong>{leaderTier.remaining} pts</strong></div><progress max="100" value={leaderProgress}/></div>}</>:<><Trophy size={40}/><strong>Quem chega primeiro?</strong><span>A primeira vitória abre a disputa.</span></>}</div>
  </section>
  <section className="mayhem-stats"><article><span><ShieldCheck size={18}/></span><div><strong>{players.length}</strong><small>JOGADORES</small></div></article><article><span><Swords size={18}/></span><div><strong>{activeMatches.length}</strong><small>PARTIDAS VÁLIDAS</small></div></article><article><span><Trophy size={18}/></span><div><strong>{totalWins}</strong><small>VITÓRIAS CONTADAS</small></div></article><article><span><Trophy size={18}/></span><div><strong>{activePlayers}</strong><small>NO RANKING</small></div></article></section>
  <div className="toolbar mayhem-toolbar"><div><p className="eyebrow">CENTRAL MAYHEM</p><h2>Atualize a classificação</h2></div>{admin&&<button className="gold" onClick={()=>{setOpen(true);setError('');setMatchId('');setChoices({});setConfirmed(false);setPlayedAt(localNow())}}>Registrar partida</button>}</div>
  <MayhemSync players={players} knownIds={matches.map((m:any)=>m.id)} onUpdated={reload}/>
  {error&&!open&&!voidId&&<p role="alert" className="mayhem-error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
  {!data?<section className="panel detail">Carregando classificação… {error&&<button onClick={()=>reload().catch(e=>setError(e.message))}>Tentar novamente</button>}</section>:<>
  {players.some((p:any)=>p.games)&&<section className="mayhem-podium">{players.filter((p:any)=>p.games).slice(0,3).map((p:any,i:number)=>{const tier=tierFor(p.points);return <article className={`podium-${i+1}`} key={p.id}><span className="podium-place">{i===0?<Trophy size={18}/>:<ShieldCheck size={18}/>} {i+1}º</span><TierIcon index={tier.index} name={tier.name}/><div><strong>{p.name}</strong><small>{tier.name}</small><b>{p.points} pts</b></div></article>})}</section>}
  <section className="panel mayhem-ranking"><div className="section-title"><div><p className="eyebrow">CLASSIFICAÇÃO GERAL</p><h2>Ranking dos jogadores</h2></div><span className="live-dot">AO VIVO</span></div><Table><thead><tr><th>#</th><th>Jogador</th><th>Elo Mayhem</th><th>Pontos</th><th>V</th><th>D</th><th>Partidas</th><th>Taxa</th></tr></thead><tbody>{players.map((p:any,i:number)=>{const tier=tierFor(p.points);return <tr className={i<3&&p.games?`rank-top rank-${i+1}`:''} key={p.id}><td><span className="rank-number">{p.games?i+1:'—'}</span></td><td><strong>{p.name}</strong><small className="mayhem-riot">{p.riot_id}#{p.tagline}{!p.active?' · Inativo':''}</small></td><td><div className="tier-label"><TierIcon index={tier.index} name={tier.name}/><span><strong>{tier.name}</strong><small>{tier.next?`${tier.remaining} pts para subir`:'Tier máximo'}</small></span></div></td><td className="score">{p.points}</td><td className="win-stat">{p.wins}</td><td>{p.losses}</td><td>{p.games||'—'}</td><td>{p.games?`${(p.rate*100).toFixed(1)}%`:'—'}</td></tr>})}</tbody></Table>{!players.length&&<p className="empty">Os jogadores aparecerão aqui depois de se cadastrar.</p>}</section>
  <section className="panel detail"><div className="toolbar"><div><p className="eyebrow">PROGRESSÃO MAYHEM</p><h2>A escalada até a Lenda do Caos</h2></div><small className="muted">Cada vitória vale 3 pontos</small></div><div className="tier-road">{TIERS.map((tier,index)=><div className="tier-card" key={tier.name}><TierIcon index={index} name={tier.name}/><strong>{tier.name}</strong><span>{index===TIERS.length-1?`${tier.min}+ pontos`:`${tier.min}–${TIERS[index+1].min-1} pontos`}</span></div>)}</div></section>
  <section className="panel detail mayhem-rules"><h2>Como funciona</h2><p>Vitória: <strong>+3 pontos</strong>. Derrota: <strong>0 pontos</strong>. Desempate por taxa de vitórias, vitórias e nome. Jogadores sem partidas ficam sem posição.</p><p>Contam apenas partidas PvP normais de ARAM Mayhem iniciadas desde {date(data.startAt)}, após o cadastro do jogador. Remakes e partidas com menos de 5 minutos não contam. ARAM comum, personalizadas e partidas do campeonato não entram nesta liga.</p><p>Qualquer usuário conectado pode atualizar. O League of Legends e o conector da Arena precisam estar abertos no mesmo computador. Registros conferidos pelo administrador ficam identificados como manuais.</p></section>
  <section className="panel detail mayhem-history"><div className="section-title"><div><p className="eyebrow">REGISTRO DE BATALHAS</p><h2><Swords size={20}/> Histórico Mayhem</h2></div><small className="muted">Mais recentes primeiro</small></div>{matches.length?matches.map((m:any)=><article className={`mayhem-match ${m.void_reason?'voided':''}`} key={m.id}><div className="match-icon"><Swords size={18}/></div><div className="match-body"><strong>{m.id}</strong><p className="muted">{date(m.played_at)} · {m.source==='riot'?'Importado da Riot':m.source==='client'?'Importado do cliente do LoL':'Conferido pelo administrador'}{m.void_reason?' · Anulada':''}</p>{m.void_reason?<p>Motivo: {m.void_reason}</p>:<div className="mayhem-outcomes">{results.filter((r:any)=>r.match_id===m.id).map((r:any)=><span className={r.win?'outcome-win':'outcome-loss'} key={r.player_id}>{players.find((p:any)=>p.id===r.player_id)?.name||'Jogador'} <b>{r.win?'+3':'0'}</b></span>)}</div>}</div>{admin&&!m.void_reason&&<button onClick={()=>{setVoidId(m.id);setReason('');setError('')}}>Anular</button>}</article>):<div className="empty"><Swords size={30}/><h3>A liga está pronta para começar</h3><p>Nenhuma partida Mayhem foi registrada. Todos começam com zero pontos.</p></div>}</section></>}
  <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="mayhem-dialog"><DialogHeader><DialogTitle>Registrar partida Mayhem</DialogTitle><DialogDescription>Somente os participantes cadastrados recebem pontos nesta liga.</DialogDescription></DialogHeader>
  <form className="form" onSubmit={e=>{e.preventDefault();save({action:mode,matchId:matchId.trim().toUpperCase(),playedAt:new Date(playedAt).toISOString(),confirmed,entries:Object.entries(choices).filter(([,v])=>v!=='none').map(([playerId,v])=>({playerId,win:v==='win'?1:0}))})}}>
  <RadioGroup value={mode} onValueChange={setMode} className="mayhem-options"><label><RadioGroupItem value="riot"/> Importar da Riot</label><label><RadioGroupItem value="manual"/> Registrar resultado conferido</label></RadioGroup>
  <label>Match ID<input required placeholder="BR1_1234567890" pattern="[Bb][Rr]1_[0-9]{5,20}" value={matchId} onChange={e=>setMatchId(e.target.value)}/></label>
  {mode==='riot'?<p className="muted">Informe o ID de uma partida finalizada. Se a Riot disponibilizar o Mayhem, serão importados os resultados dos Riot IDs cadastrados. Nenhum resultado é estimado.</p>:<><label>Início da partida<input required type="datetime-local" value={playedAt} onChange={e=>setPlayedAt(e.target.value)}/></label><p className="muted">Selecione o resultado de quem participou. Deixe os demais como “Não jogou”.</p>{players.map((p:any)=><fieldset className="mayhem-choice" key={p.id}><legend>{p.name}</legend><RadioGroup className="mayhem-options" value={choices[p.id]||'none'} onValueChange={v=>setChoices({...choices,[p.id]:v})}><label><RadioGroupItem value="none"/> Não jogou</label><label><RadioGroupItem value="win"/> Vitória</label><label><RadioGroupItem value="loss"/> Derrota</label></RadioGroup></fieldset>)}<label className="mayhem-options"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/> Conferi o resultado: Mayhem PvP normal, finalizado, sem remake, com pelo menos 5 minutos.</label></>}
  {error&&<p role="alert" className="mayhem-error">{error}</p>}<button className="gold" disabled={busy||(mode==='manual'&&!confirmed)}>{busy?'Registrando…':mode==='riot'?'Consultar e importar':'Salvar resultado Mayhem'}</button></form></DialogContent></Dialog>
  <Dialog open={!!voidId} onOpenChange={v=>{if(!v&&!busy)setVoidId('')}}><DialogContent><DialogHeader><DialogTitle>Anular resultado Mayhem</DialogTitle><DialogDescription>Remove os pontos desta partida da classificação Mayhem e mantém o registro no histórico.</DialogDescription></DialogHeader><form className="form" onSubmit={e=>{e.preventDefault();save({action:'void',matchId:voidId,reason})}}><label>Motivo<input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy} className="gold">Confirmar anulação</button></form></DialogContent></Dialog>
 </div>;
}
