'use client';
import {useState,useEffect,useCallback} from 'react';
import {Trophy, Swords, ShieldCheck} from 'lucide-react';
import {Table} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
const date=(v:string)=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
const localNow=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
export default function Mayhem({admin}:{admin:boolean}) {
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [open,setOpen]=useState(false),[mode,setMode]=useState('riot'),[matchId,setMatchId]=useState(''),[playedAt,setPlayedAt]=useState(localNow),[choices,setChoices]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false);
 const [voidId,setVoidId]=useState(''),[reason,setReason]=useState('');
 const reload=useCallback(async()=>{const r=await fetch('/api/mayhem',{cache:'no-store'}),b:any=await r.json();if(!r.ok)throw new Error(b.error);setData(b)},[]);
 useEffect(()=>{reload().catch(e=>setError(e.message));const timer=setInterval(()=>reload().catch(()=>{}),20000);return()=>clearInterval(timer)},[reload]);
 async function save(payload:any) {
  setBusy(true);setError('');setNotice('');
  try {const r=await fetch('/api/mayhem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),b:any=await r.json();if(!r.ok)throw new Error(b.error);await reload();setOpen(false);setVoidId('');setNotice(payload.action==='void'?'Partida anulada. Classificação Mayhem recalculada.':'Resultado salvo no ranking Mayhem.');}
  catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}
 }
 const players=data?.ranking||[],matches=data?.matches||[],results=data?.results||[],leader=players.find((p:any)=>p.games>0);
 return <div className="mayhem">
  <section className="panel mayhem-hero">
   <div><p className="eyebrow">LIGA DA COMUNIDADE · ARAM MAYHEM</p><h2>O caos tem sua classificação.</h2><p>Dispute posições com os amigos nas partidas PvP de Mayhem. Cada vitória vale 3 pontos nesta liga.</p><span className="badge"><ShieldCheck size={14}/> Pontuação independente do campeonato</span></div>
   <div className="mayhem-leader"><Trophy size={30}/><small>{leader?'LÍDER DA LIGA':'TEMPORADA ABERTA'}</small><strong>{leader?.name||'Quem chega primeiro?'}</strong><span>{leader?`${leader.points} pontos · ${leader.wins} vitórias`:'A primeira partida define o início da disputa.'}</span></div>
  </section>
  <div className="toolbar"><p className="muted">{players.length} jogadores · {matches.filter((m:any)=>!m.void_reason).length} partidas registradas</p>{admin&&<button className="gold" onClick={()=>{setOpen(true);setError('');setMatchId('');setChoices({});setConfirmed(false);setPlayedAt(localNow())}}>Registrar partida Mayhem</button>}</div>
  {error&&!open&&!voidId&&<p role="alert" className="mayhem-error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
  {!data?<section className="panel detail">Carregando classificação… {error&&<button onClick={()=>reload().catch(e=>setError(e.message))}>Tentar novamente</button>}</section>:<>
  <section className="panel"><Table><thead><tr><th>Posição</th><th>Jogador</th><th>Pontos Mayhem</th><th>Vitórias</th><th>Derrotas</th><th>Partidas</th><th>Taxa de vitórias</th></tr></thead><tbody>{players.map((p:any,i:number)=><tr key={p.id}><td>{p.games?`${i+1}º`:'—'}</td><td><strong>{p.name}</strong><small className="mayhem-riot">{p.riot_id}#{p.tagline}{!p.active?' · Inativo':''}</small></td><td className="score">{p.points}</td><td>{p.wins}</td><td>{p.losses}</td><td>{p.games||'Ainda não jogou'}</td><td>{p.games?`${(p.rate*100).toFixed(1)}%`:'—'}</td></tr>)}</tbody></Table>{!players.length&&<p className="empty">Os jogadores aparecerão aqui depois de se cadastrar.</p>}</section>
  <section className="panel detail mayhem-rules"><h2>Como funciona</h2><p>Vitória: <strong>+3 pontos</strong>. Derrota: <strong>0 pontos</strong>. Desempate por taxa de vitórias, vitórias e nome. Jogadores sem partidas ficam sem posição.</p><p>Contam apenas partidas PvP normais de ARAM Mayhem iniciadas desde {date(data.startAt)}, após o cadastro do jogador. Remakes e partidas com menos de 5 minutos não contam. ARAM comum, personalizadas e partidas do campeonato não entram nesta liga.</p><p>Ranking comunitário por resultados; não representa elo ou MMR oficial da Riot. A importação depende da disponibilidade da partida na Riot. Registros conferidos pelo administrador ficam identificados como manuais.</p></section>
  <section className="panel detail"><div className="toolbar"><h2><Swords size={20}/> Histórico Mayhem</h2><small className="muted">Mais recentes primeiro</small></div>{matches.length?matches.map((m:any)=><article className="mayhem-match" key={m.id}><div><strong>{m.id}</strong><p className="muted">{date(m.played_at)} · {m.source==='riot'?'Importado da Riot':'Conferido pelo administrador'}{m.void_reason?' · Anulada':''}</p>{m.void_reason?<p>Motivo: {m.void_reason}</p>:<div className="mayhem-outcomes">{results.filter((r:any)=>r.match_id===m.id).map((r:any)=><span className={r.win?'badge':'muted'} key={r.player_id}>{players.find((p:any)=>p.id===r.player_id)?.name||'Jogador'} · {r.win?'Vitória +3':'Derrota +0'}</span>)}</div>}</div>{admin&&!m.void_reason&&<button onClick={()=>{setVoidId(m.id);setReason('');setError('')}}>Anular resultado</button>}</article>):<div className="empty"><Swords size={30}/><h3>A liga está pronta para começar</h3><p>Nenhuma partida Mayhem foi registrada. Todos começam com zero pontos.</p></div>}</section></>}
  <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="mayhem-dialog"><DialogHeader><DialogTitle>Registrar partida Mayhem</DialogTitle><DialogDescription>Somente os participantes cadastrados recebem pontos nesta liga.</DialogDescription></DialogHeader>
  <form className="form" onSubmit={e=>{e.preventDefault();save({action:mode,matchId:matchId.trim().toUpperCase(),playedAt:new Date(playedAt).toISOString(),confirmed,entries:Object.entries(choices).filter(([,v])=>v!=='none').map(([playerId,v])=>({playerId,win:v==='win'?1:0}))})}}>
  <RadioGroup value={mode} onValueChange={setMode} className="mayhem-options"><label><RadioGroupItem value="riot"/> Importar da Riot</label><label><RadioGroupItem value="manual"/> Registrar resultado conferido</label></RadioGroup>
  <label>Match ID<input required placeholder="BR1_1234567890" pattern="[Bb][Rr]1_[0-9]{5,20}" value={matchId} onChange={e=>setMatchId(e.target.value)}/></label>
  {mode==='riot'?<p className="muted">Informe o ID de uma partida finalizada. Se a Riot disponibilizar o Mayhem, serão importados os resultados dos Riot IDs cadastrados. Nenhum resultado é estimado.</p>:<><label>Início da partida<input required type="datetime-local" value={playedAt} onChange={e=>setPlayedAt(e.target.value)}/></label><p className="muted">Selecione o resultado de quem participou. Deixe os demais como “Não jogou”.</p>{players.map((p:any)=><fieldset className="mayhem-choice" key={p.id}><legend>{p.name}</legend><RadioGroup className="mayhem-options" value={choices[p.id]||'none'} onValueChange={v=>setChoices({...choices,[p.id]:v})}><label><RadioGroupItem value="none"/> Não jogou</label><label><RadioGroupItem value="win"/> Vitória</label><label><RadioGroupItem value="loss"/> Derrota</label></RadioGroup></fieldset>)}<label className="mayhem-options"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/> Conferi o resultado: Mayhem PvP normal, finalizado, sem remake, com pelo menos 5 minutos.</label></>}
  {error&&<p role="alert" className="mayhem-error">{error}</p>}<button className="gold" disabled={busy||(mode==='manual'&&!confirmed)}>{busy?'Registrando…':mode==='riot'?'Consultar e importar':'Salvar resultado Mayhem'}</button></form></DialogContent></Dialog>
  <Dialog open={!!voidId} onOpenChange={v=>{if(!v&&!busy)setVoidId('')}}><DialogContent><DialogHeader><DialogTitle>Anular resultado Mayhem</DialogTitle><DialogDescription>Remove os pontos desta partida da classificação Mayhem e mantém o registro no histórico.</DialogDescription></DialogHeader><form className="form" onSubmit={e=>{e.preventDefault();save({action:'void',matchId:voidId,reason})}}><label>Motivo<input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy} className="gold">Confirmar anulação</button></form></DialogContent></Dialog>
 </div>;
}
